# Monitoring and alerts: Uptime Kuma (+ healthchecks.io heartbeat). See README.md.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - uptime-kuma.yaml
  - ingress.yaml
  - heartbeat.yaml
  - kuma-config.yaml
configMapGenerator:
  - name: kuma-config
    files:
      - kuma-config/configure.js
      - kuma-config/monitors.json
