---
- name: NFS client prep
  hosts: k3s_cluster
  gather_facts: true
  become: true
  roles:
    - role: nfs

# Upstream k3s install (prereq, airgap, raspberrypi, k3s_server, k3s_agent)
- name: Install k3s
  ansible.builtin.import_playbook: k3s.orchestration.site

- name: Setup cert-manager
  hosts: server[0]
  gather_facts: false
  become: false
  roles:
    - role: cert_manager
      when: install_cert_manager | default(false)

- name: Setup NFS CSI driver
  hosts: server[0]
  gather_facts: false
  become: false
  roles:
    - role: nfs_csi
      when: install_nfs_csi | default(false)

- name: Setup Longhorn
  hosts: k3s_cluster
  gather_facts: true
  become: true
  roles:
    - role: longhorn
      when: install_longhorn | default(false)
